/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_REMOTETESTSITE_PROTO_ACK_PB_H_INCLUDED
#define PB_REMOTETESTSITE_PROTO_ACK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RemoteTestSite_Ack {
    char dummy_field;
} RemoteTestSite_Ack;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RemoteTestSite_Ack_init_default          {0}
#define RemoteTestSite_Ack_init_zero             {0}

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */
#define RemoteTestSite_Ack_FIELDLIST(X, a) \

#define RemoteTestSite_Ack_CALLBACK NULL
#define RemoteTestSite_Ack_DEFAULT NULL

extern const pb_msgdesc_t RemoteTestSite_Ack_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RemoteTestSite_Ack_fields &RemoteTestSite_Ack_msg

/* Maximum encoded size of messages (where known) */
#define REMOTETESTSITE_PROTO_ACK_PB_H_MAX_SIZE   RemoteTestSite_Ack_size
#define RemoteTestSite_Ack_size                  0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
