/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_REMOTETESTSITE_PROTO_COMMAND_PB_H_INCLUDED
#define PB_REMOTETESTSITE_PROTO_COMMAND_PB_H_INCLUDED
#include <pb.h>
#include "proto/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RemoteTestSite_Command_Commands {
    RemoteTestSite_Command_Commands_COMMAND_UNSPECIFIED = 0,
    RemoteTestSite_Command_Commands_COMMAND_ACTIVATE_PUMP = 1
} RemoteTestSite_Command_Commands;

/* Struct definitions */
typedef struct _RemoteTestSite_Command {
    bool has_duration;
    RemoteTestSite_Timestamp duration;
    bool has_command;
    RemoteTestSite_Command_Commands command;
} RemoteTestSite_Command;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RemoteTestSite_Command_Commands_MIN RemoteTestSite_Command_Commands_COMMAND_UNSPECIFIED
#define _RemoteTestSite_Command_Commands_MAX RemoteTestSite_Command_Commands_COMMAND_ACTIVATE_PUMP
#define _RemoteTestSite_Command_Commands_ARRAYSIZE ((RemoteTestSite_Command_Commands)(RemoteTestSite_Command_Commands_COMMAND_ACTIVATE_PUMP+1))

#define RemoteTestSite_Command_command_ENUMTYPE RemoteTestSite_Command_Commands


/* Initializer values for message structs */
#define RemoteTestSite_Command_init_default      {false, RemoteTestSite_Timestamp_init_default, false, _RemoteTestSite_Command_Commands_MIN}
#define RemoteTestSite_Command_init_zero         {false, RemoteTestSite_Timestamp_init_zero, false, _RemoteTestSite_Command_Commands_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define RemoteTestSite_Command_duration_tag      1
#define RemoteTestSite_Command_command_tag       2

/* Struct field encoding specification for nanopb */
#define RemoteTestSite_Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  duration,          1) \
X(a, STATIC,   OPTIONAL, UENUM,    command,           2)
#define RemoteTestSite_Command_CALLBACK NULL
#define RemoteTestSite_Command_DEFAULT NULL
#define RemoteTestSite_Command_duration_MSGTYPE RemoteTestSite_Timestamp

extern const pb_msgdesc_t RemoteTestSite_Command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RemoteTestSite_Command_fields &RemoteTestSite_Command_msg

/* Maximum encoded size of messages (where known) */
#define REMOTETESTSITE_PROTO_COMMAND_PB_H_MAX_SIZE RemoteTestSite_Command_size
#define RemoteTestSite_Command_size              21

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
