/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_REMOTETESTSITE_PROTO_MEASUREMENT_INFO_PB_H_INCLUDED
#define PB_REMOTETESTSITE_PROTO_MEASUREMENT_INFO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RemoteTestSite_MeasurementInfo {
    RemoteTestSite_MeasurementInfo_MEASUREMENT_INFO_UNSPECIFIED = 0,
    RemoteTestSite_MeasurementInfo_MEASUREMENT_INFO_THERM200_TEMPERATURE = 1,
    RemoteTestSite_MeasurementInfo_MEASUREMENT_INFO_VH400_VWC = 2,
    RemoteTestSite_MeasurementInfo_MEASUREMENT_INFO_MURATA_TEMPERATURE = 3,
    RemoteTestSite_MeasurementInfo_MEASUREMENT_INFO_MURATA_VWC = 4,
    RemoteTestSite_MeasurementInfo_MEASUREMENT_INFO_MURATA_EC_BULK = 5,
    RemoteTestSite_MeasurementInfo_MEASUREMENT_INFO_MURATA_EC_PORE = 6
} RemoteTestSite_MeasurementInfo;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RemoteTestSite_MeasurementInfo_MIN RemoteTestSite_MeasurementInfo_MEASUREMENT_INFO_UNSPECIFIED
#define _RemoteTestSite_MeasurementInfo_MAX RemoteTestSite_MeasurementInfo_MEASUREMENT_INFO_MURATA_EC_PORE
#define _RemoteTestSite_MeasurementInfo_ARRAYSIZE ((RemoteTestSite_MeasurementInfo)(RemoteTestSite_MeasurementInfo_MEASUREMENT_INFO_MURATA_EC_PORE+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
