/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_REMOTETESTSITE_PROTO_MEASUREMENT_TYPE_PB_H_INCLUDED
#define PB_REMOTETESTSITE_PROTO_MEASUREMENT_TYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RemoteTestSite_MeasurementType {
    RemoteTestSite_MeasurementType_MEASUREMENT_TYPE_UNSPECIFIED = 0,
    RemoteTestSite_MeasurementType_MEASUREMENT_TYPE_TEMPERATURE = 1,
    RemoteTestSite_MeasurementType_MEASUREMENT_TYPE_VWC = 2,
    RemoteTestSite_MeasurementType_MEASUREMENT_TYPE_EC_BULK = 3,
    RemoteTestSite_MeasurementType_MEASUREMENT_TYPE_EC_PORE = 4
} RemoteTestSite_MeasurementType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RemoteTestSite_MeasurementType_MIN RemoteTestSite_MeasurementType_MEASUREMENT_TYPE_UNSPECIFIED
#define _RemoteTestSite_MeasurementType_MAX RemoteTestSite_MeasurementType_MEASUREMENT_TYPE_EC_PORE
#define _RemoteTestSite_MeasurementType_ARRAYSIZE ((RemoteTestSite_MeasurementType)(RemoteTestSite_MeasurementType_MEASUREMENT_TYPE_EC_PORE+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
