/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_REMOTETESTSITE_PROTO_PING_PB_H_INCLUDED
#define PB_REMOTETESTSITE_PROTO_PING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RemoteTestSite_Ping {
    char dummy_field;
} RemoteTestSite_Ping;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RemoteTestSite_Ping_init_default         {0}
#define RemoteTestSite_Ping_init_zero            {0}

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */
#define RemoteTestSite_Ping_FIELDLIST(X, a) \

#define RemoteTestSite_Ping_CALLBACK NULL
#define RemoteTestSite_Ping_DEFAULT NULL

extern const pb_msgdesc_t RemoteTestSite_Ping_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RemoteTestSite_Ping_fields &RemoteTestSite_Ping_msg

/* Maximum encoded size of messages (where known) */
#define REMOTETESTSITE_PROTO_PING_PB_H_MAX_SIZE  RemoteTestSite_Ping_size
#define RemoteTestSite_Ping_size                 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
