/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_REMOTETESTSITE_PROTO_RESPONSE_PB_H_INCLUDED
#define PB_REMOTETESTSITE_PROTO_RESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RemoteTestSite_ResponseCode {
    RemoteTestSite_ResponseCode_ERROR_CODE_UNSPECIFIED = 0,
    RemoteTestSite_ResponseCode_ERROR_CODE_OK = 1,
    RemoteTestSite_ResponseCode_ERROR_CODE_UNEXPECTED_PARAMETER = 2,
    RemoteTestSite_ResponseCode_ERROR_CODE_INVALLID_PARAMETER = 3
} RemoteTestSite_ResponseCode;

/* Struct definitions */
typedef struct _RemoteTestSite_Response {
    bool has_response_code;
    RemoteTestSite_ResponseCode response_code;
} RemoteTestSite_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RemoteTestSite_ResponseCode_MIN RemoteTestSite_ResponseCode_ERROR_CODE_UNSPECIFIED
#define _RemoteTestSite_ResponseCode_MAX RemoteTestSite_ResponseCode_ERROR_CODE_INVALLID_PARAMETER
#define _RemoteTestSite_ResponseCode_ARRAYSIZE ((RemoteTestSite_ResponseCode)(RemoteTestSite_ResponseCode_ERROR_CODE_INVALLID_PARAMETER+1))

#define RemoteTestSite_Response_response_code_ENUMTYPE RemoteTestSite_ResponseCode


/* Initializer values for message structs */
#define RemoteTestSite_Response_init_default     {false, _RemoteTestSite_ResponseCode_MIN}
#define RemoteTestSite_Response_init_zero        {false, _RemoteTestSite_ResponseCode_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define RemoteTestSite_Response_response_code_tag 1

/* Struct field encoding specification for nanopb */
#define RemoteTestSite_Response_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    response_code,     1)
#define RemoteTestSite_Response_CALLBACK NULL
#define RemoteTestSite_Response_DEFAULT NULL

extern const pb_msgdesc_t RemoteTestSite_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RemoteTestSite_Response_fields &RemoteTestSite_Response_msg

/* Maximum encoded size of messages (where known) */
#define REMOTETESTSITE_PROTO_RESPONSE_PB_H_MAX_SIZE RemoteTestSite_Response_size
#define RemoteTestSite_Response_size             2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
