/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_REMOTETESTSITE_PROTO_RESPONSE_PB_H_INCLUDED
#define PB_REMOTETESTSITE_PROTO_RESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RemoteTestSite_ErrorCode {
    RemoteTestSite_ErrorCode_ERROR_CODE_UNSPECIFIED = 0,
    RemoteTestSite_ErrorCode_ERROR_CODE_OK = 1,
    RemoteTestSite_ErrorCode_ERROR_CODE_UNEXPECTED_PARAMETER = 2,
    RemoteTestSite_ErrorCode_ERROR_CODE_INVALLID_PARAMETER = 3
} RemoteTestSite_ErrorCode;

/* Struct definitions */
typedef struct _RemoteTestSite_Response {
    bool has_error_code;
    RemoteTestSite_ErrorCode error_code;
    pb_callback_t error;
} RemoteTestSite_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RemoteTestSite_ErrorCode_MIN RemoteTestSite_ErrorCode_ERROR_CODE_UNSPECIFIED
#define _RemoteTestSite_ErrorCode_MAX RemoteTestSite_ErrorCode_ERROR_CODE_INVALLID_PARAMETER
#define _RemoteTestSite_ErrorCode_ARRAYSIZE ((RemoteTestSite_ErrorCode)(RemoteTestSite_ErrorCode_ERROR_CODE_INVALLID_PARAMETER+1))

#define RemoteTestSite_Response_error_code_ENUMTYPE RemoteTestSite_ErrorCode


/* Initializer values for message structs */
#define RemoteTestSite_Response_init_default     {false, _RemoteTestSite_ErrorCode_MIN, {{NULL}, NULL}}
#define RemoteTestSite_Response_init_zero        {false, _RemoteTestSite_ErrorCode_MIN, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define RemoteTestSite_Response_error_code_tag   1
#define RemoteTestSite_Response_error_tag        2

/* Struct field encoding specification for nanopb */
#define RemoteTestSite_Response_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    error_code,        1) \
X(a, CALLBACK, OPTIONAL, STRING,   error,             2)
#define RemoteTestSite_Response_CALLBACK pb_default_field_callback
#define RemoteTestSite_Response_DEFAULT NULL

extern const pb_msgdesc_t RemoteTestSite_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RemoteTestSite_Response_fields &RemoteTestSite_Response_msg

/* Maximum encoded size of messages (where known) */
/* RemoteTestSite_Response_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
