/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_REMOTETESTSITE_PROTO_UPDATE_PB_H_INCLUDED
#define PB_REMOTETESTSITE_PROTO_UPDATE_PB_H_INCLUDED
#include <pb.h>
#include "proto/measurement_info.pb.h"
#include "proto/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RemoteTestSite_Update_UpdateFrequency {
    bool has_info;
    RemoteTestSite_MeasurementInfo info;
    bool has_frequency;
    RemoteTestSite_Timestamp frequency;
} RemoteTestSite_Update_UpdateFrequency;

typedef struct _RemoteTestSite_Update {
    pb_size_t which_UpdateType;
    union {
        RemoteTestSite_Update_UpdateFrequency update_frequency; /* UpdateFirmware update_firmware = 2; */
    } UpdateType;
} RemoteTestSite_Update;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RemoteTestSite_Update_init_default       {0, {RemoteTestSite_Update_UpdateFrequency_init_default}}
#define RemoteTestSite_Update_UpdateFrequency_init_default {false, _RemoteTestSite_MeasurementInfo_MIN, false, RemoteTestSite_Timestamp_init_default}
#define RemoteTestSite_Update_init_zero          {0, {RemoteTestSite_Update_UpdateFrequency_init_zero}}
#define RemoteTestSite_Update_UpdateFrequency_init_zero {false, _RemoteTestSite_MeasurementInfo_MIN, false, RemoteTestSite_Timestamp_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define RemoteTestSite_Update_UpdateFrequency_info_tag 1
#define RemoteTestSite_Update_UpdateFrequency_frequency_tag 2
#define RemoteTestSite_Update_update_frequency_tag 1

/* Struct field encoding specification for nanopb */
#define RemoteTestSite_Update_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (UpdateType,update_frequency,UpdateType.update_frequency),   1)
#define RemoteTestSite_Update_CALLBACK NULL
#define RemoteTestSite_Update_DEFAULT NULL
#define RemoteTestSite_Update_UpdateType_update_frequency_MSGTYPE RemoteTestSite_Update_UpdateFrequency

#define RemoteTestSite_Update_UpdateFrequency_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    info,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  frequency,         2)
#define RemoteTestSite_Update_UpdateFrequency_CALLBACK NULL
#define RemoteTestSite_Update_UpdateFrequency_DEFAULT NULL
#define RemoteTestSite_Update_UpdateFrequency_frequency_MSGTYPE RemoteTestSite_Timestamp

extern const pb_msgdesc_t RemoteTestSite_Update_msg;
extern const pb_msgdesc_t RemoteTestSite_Update_UpdateFrequency_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RemoteTestSite_Update_fields &RemoteTestSite_Update_msg
#define RemoteTestSite_Update_UpdateFrequency_fields &RemoteTestSite_Update_UpdateFrequency_msg

/* Maximum encoded size of messages (where known) */
#define REMOTETESTSITE_PROTO_UPDATE_PB_H_MAX_SIZE RemoteTestSite_Update_size
#define RemoteTestSite_Update_UpdateFrequency_size 21
#define RemoteTestSite_Update_size               23

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
