/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "proto/timestamp.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RemoteTestSite_Timestamp, RemoteTestSite_Timestamp, AUTO)



