/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "proto/update.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RemoteTestSite_Update, RemoteTestSite_Update, AUTO)


PB_BIND(RemoteTestSite_Update_UpdateFrequency, RemoteTestSite_Update_UpdateFrequency, AUTO)


PB_BIND(RemoteTestSite_Update_UpdateFirmware, RemoteTestSite_Update_UpdateFirmware, AUTO)



